config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :items, :only => [:index, :show]
  resources :line_items, :only => [:index, :create, :destroy]

  scope 'api/v1' do
    resources :line_items, :only => [:index, :create, :destroy, :update], controller: 'api/v1/line_items'
    resources :items, :only => [:index], controller: 'api/v1/items'
    resources :share_queues, :only => [:index, :create], controller: 'api/v1/share_queues'
  end

  scope 'admin' do
    get '/', :to => 'admin/admin#index'
    post '/fetch', :to => 'admin/admin#fetch'
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  self.per_page = 20

  has_many :line_items
  has_many :users, :through => :line_items
  belongs_to :search_node

  validates :title, presence: true
  validates :image_url, presence: true
  validates :url, presence: true
  validates :price, presence: true

  scope :unrated_by, lambda { |user|
    where("not exists (select id from line_items where line_items.item_id = items.id AND line_items.user_id = ?)", user.id)
  }

  scope :liked_by, lambda { |user|
    joins("left outer join line_items as i on items.id = i.item_id")
    .where("i.liked = ?", true)
    .where("i.user_id = ?", user.id)
  }

  scope :disliked_by, lambda { |user|
    joins("left outer join line_items as i on items.id = i.item_id")
    .where("i.liked = false")
    .where("i.user_id = ?", user.id)
  }

  scope :category, lambda { |category_id|
    where(category: category_id)
  }

  def is_liked?(user)
    user.line_items.where(item_id: self.id, liked: true).exists?
  end

  def category
    search_node.category
  end

  def parent_category
    search_node.parent_category
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  belongs_to :share_queue

  validates_presence_of :user_id, :item_id
  validates_inclusion_of :liked, in: [true, false, nil]
  validates :user_id, uniqueness: { :scope => :item_id }

  def can_destroy?(user)
    unless user.id == self.user.id
      errors.add(:base, "You must own a line_item to destroy it")
      return false
    end
    return true
  end
end

app/models/log.rb
class Log < ActiveRecord::Base

  scope :searches_for_node, lambda { |node|
    where(search_node_id: node.id).order("created_at DESC")
  }

end

app/models/search_node.rb
class SearchNode < ActiveRecord::Base
  scope :by_vendor, -> vendor { where(vendor: vendor) }
end

app/models/share_queue.rb
class ShareQueue < ActiveRecord::Base
  has_many :line_items

  validates :recipient_id, presence: true
  validates :creator_id, presence: true

  scope :created_by, lambda { |user|
    where(creator_id: user.id)
  }

  scope :received_by, lambda { |user|
    where(recipient_id: user.id)
  }

  def complete?
    line_items.where(liked: nil).empty?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :line_items
  has_many :items, :through => :line_items

  def self.authenticate(guid)
    User.find_or_create_by(guid: guid) do |user|
      user.email = guid
    end
  end

  def admin?
    admin
  end
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    before_filter :require_admin

    def index
      @delayed_jobs = Delayed::Job.all
    end

    def fetch
      fetcher = Services::Popshops::ItemFetcher.new(page: 1, category: params[:category])
      count = fetcher.do_request

      flash[:notice] = "Added #{count} additional items"

      redirect_to '/admin'
    end
  end
end

app/controllers/api/v1/api_controller.rb
module Api
  module V1
    class ApiController < ApplicationController
      before_filter :authenticate_user!
      before_filter :validate_params

      def render_json(model, success)
        if success
          render json: model
        else
          render json: { errors: model.errors }, status: 422
        end
      end
    end
  end
end

app/controllers/api/v1/items_controller.rb
module Api
  module V1
    class ItemsController < Api::V1::ApiController
      def index
        items = Item.where(nil)
        items = items.liked_by(current_user) if params[:liked]
        items = items.disliked_by(current_user) if params[:disliked]
        items = items.unrated_by(current_user) if params[:unrated]

        render json: items.paginate(page: params[:page]).as_json
      end

      private

      def validate_params
        param! :page, Integer, default: 1
        param! :liked, :boolean
        param! :disliked, :boolean
        param! :unrated, :boolean
      end
    end
  end
end

app/controllers/api/v1/line_items_controller.rb
module Api
  module V1
    class LineItemsController < Api::V1::ApiController
      def index
        @line_items = LineItem.paginate(page: params[:page])
        render json: @line_items
      end

      def create
        attrs = { liked: params[:liked], item_id: params[:item_id] }
        line_item = current_user.line_items.build(attrs)

        render_json(line_item, line_item.save && current_user.id == line_item.user_id)
      end

      def update
        line_item = LineItem.find_by_id(params[:id])

        render_json(line_item, line_item.update_attributes(liked: params[:liked]))
      end

      def destroy
        line_item = LineItem.find_by_id(params[:id])
        if line_item.can_destroy?(current_user)
          line_item.destroy
        end

        render json: line_item
      end

      private

      def validate_params
        param! :id, Integer
        param! :item_id, Integer
        param! :liked, :boolean
        param! :page, Integer, default: 1
      end
    end
  end
end

app/controllers/api/v1/share_queues_controller.rb
module Api
  module V1
    class ShareQueuesController < Api::V1::ApiController
      def index
        share_queues = ShareQueue.paginate(page: params[:page])
        share_queues = share_queues.created_by(current_user) if params[:created]
        share_queues = share_queues.received_by(current_user) if params[:received]

        render json: share_queues
      end

      def create
        share_queue = build_queue

        render_json(share_queue, true)
      end

      private

      def build_queue
        attrs = { creator_id: current_user.id, recipient_id: params[:recipient_id] }
        share_queue = ShareQueue.create(attrs)

        ActiveRecord::Base.transaction do
          params[:item_ids].each { |item_id| find_or_build_line_item(share_queue.id, item_id) }
        end
        share_queue
      end

      def find_or_build_line_item(share_queue_id, item_id)
        line_item = LineItem.find_or_create_by(item_id: item_id, user_id: params[:recipient_id])
        line_item.update_attributes(liked: nil, share_queue_id: share_queue_id)
      end

      def validate_params
        param! :created, :boolean, default: false
        param! :received, :boolean, default: false
        param! :page, Integer, default: 1
        param! :recipient_id, Integer
        param! :item_ids, Array
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :authenticate_user!
  before_action :parse_params

  def require_admin
    unless current_user.admin?
      redirect_to 'users/sign_in'
    end
  end

  def parse_params
    params.each do |k, v|
      params[k] = true if v == 'true'
      params[k] = false if v == 'false'
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.paginate(:page => params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def index
    @line_items = LineItem.paginate(:page => params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/amazon_items_helper.rb
module AmazonItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/admin/admin/index.html.erb
<div class="row">
  <h3>Manually fetch a category</h3>
  <%= form_tag("/admin/fetch", method: "post") do %>
    <%= label_tag(:category, "Fetch by category:") %>
    <%= text_field_tag(:category) %>
    <%= submit_tag("Search") %>
  <% end %>
</div>

<hr />

<div class="row">
  <h3>Active Delayed Jobs</h3>
  <ul>
    <% @delayed_jobs.each do |job| %>
      <%= job %>
    <% end %>
    <% if @delayed_jobs.count == 0 %>
      <em>There are no delayed jobs.</em>
    <% end %>
  </li>
</div>

app/views/amazon_items/index.html.erb
<div class="row">
  <div>Select a search type</div>
  <select class="search-type">
    <option>ItemSearch</option>
  </select>
</div>

<div class="row">
  <div>Enter a search term</div>
  <input class="search-term"></input>
</div>

<div class="row">
  <div>Enter some options</div>
  <div>
    <input class="option1-key"></input>
    <input class="option1-value"></input>
  </div>
  <div>
    <input class="option2-key"></input>
    <input class="option2-value"></input>
  </div>
  <div>
    <input class="option3-key"></input>
    <input class="option3-value"></input>
  </div>
  <div>
    <input class="option4-key"></input>
    <input class="option4-value"></input>
  </div>
  <div>
    <input class="option5-key"></input>
    <input class="option5-value"></input>
  </div>
</div>

<div class="row">
  <button class="search-button">Search</button>
</div>

app/views/items/_item.html.erb
<td><%= item.title %></td>
<td><%= item.price %></td>
<td><img src="<%= item.image_url %>"></img></td>

app/views/items/index.html.erb
<div class="container">
  <div class="row">
    <h3>Items</h3>
    <table class="table">
      <tbody>
        <thead>
          <td>Name</td>
          <td>Price</td>
          <td>Thumbnail</td>
          <td>Item Detail</td>
          <td>Like This!</td>
        </thead>
        <% @items.each do |item| %>
          <tr data-id=<%= item.id %>>
            <%= render item %>
            <td><a href='<%= item_path(item) %>'>View Item</a></td>
            <td>
              <button class="btn btn-primary like <%= 'hidden' if item.is_liked?(current_user) %>">
                Like
              </button>
              <button class="btn btn-warning unlike <%= 'hidden' unless item.is_liked?(current_user) %>">
                Unlike
              </button>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @items %>
  </div>
</div>

<script>
  $(new Amzn.ItemsView)
</script>

app/views/items/show.html.erb
<div class="container">
  <div class="row">
    <h3>Item Details</h3>
    <%= render @item %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Amzn" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Amzn" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <div class="container container-fluid">
         <%= yield %>
       </div>
    </main>
  </body>
</html>

app/views/line_items/_line_item.html.erb
<td><%= line_item.item.title %></td>
<td><%= line_item.item.price %></td>
<td><img src="<%= line_item.item.image_url %>"></img></td>
<td><a href='<%= item_path(line_item.item) %>'>View Item</a></td>
<td><%= line_item.user.name %></td>

app/views/line_items/index.html.erb
<div class="container">
  <div class="row">
    <h3>Items</h3>
    <table class="table">
      <thead>
        <td>Name</td>
        <td>Price</td>
        <td>Thumbnail</td>
        <td>Item Detail</td>
        <td>Liked By</td>
      </thead>
      <tbody>
        <% if @line_items.count > 0 %>
          <% @line_items.each do |line_item| %>
          <tr>
            <%= render line_item %>
          </tr>
          <% end %>
        <% else %>
          Nobody has liked anything.
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @line_items %>
  </div>
</div>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>